
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Principal extends javax.swing.JFrame {

    Conexion c = new Conexion();
    CuerpoDeAgua[] ca = new CuerpoDeAgua[1000000];

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        c.conectar();//conecta a BD reto4
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtirca = new javax.swing.JTextField();
        cbo_cuerpoagua = new javax.swing.JComboBox<>();
        cbo_tipoagua = new javax.swing.JComboBox<>();
        btn_ingresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtmunicipio = new javax.swing.JTextField();
        btn_obtenerdatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnconsultar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cuerposdeaguamedio = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Tipo Cuerpo de Agua");

        jLabel6.setText("Tipo de Agua");

        jLabel7.setText("IRCA");

        cbo_cuerpoagua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laguna", "Rio" }));
        cbo_cuerpoagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_cuerpoaguaActionPerformed(evt);
            }
        });

        cbo_tipoagua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dulce", "Salada" }));
        cbo_tipoagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipoaguaActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.setEnabled(false);
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO IRCA");

        jLabel2.setText("Nombre");

        jLabel3.setText("Id Cuerpo de Agua");

        jLabel4.setText("Municipio");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtmunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmunicipioActionPerformed(evt);
            }
        });

        btn_obtenerdatos.setText("Obtener Datos");
        btn_obtenerdatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obtenerdatosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.setEnabled(false);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.setEnabled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Numeros de Cuerpo De Agua Medio o Inferior:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        cuerposdeaguamedio.setText("Lista de cuerpos de Agua Medio");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel9.setText("IRCA mas bajo: ");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_obtenerdatos)
                            .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnombre)
                                .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtirca)
                                    .addComponent(cbo_tipoagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbo_cuerpoagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cuerposdeaguamedio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbo_cuerpoagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbo_tipoagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtirca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar)
                    .addComponent(btneliminar)
                    .addComponent(btn_obtenerdatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btncancelar)
                    .addComponent(btn_ingresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cuerposdeaguamedio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed

        String Nombre = txtnombre.getText();
        int idCuerpoAgua = Integer.parseInt(txtid.getText());
        String Municipio = txtmunicipio.getText();
        String TipoCuerpoAgua = cbo_cuerpoagua.getSelectedItem().toString();
        String TipoAgua = cbo_tipoagua.getSelectedItem().toString();
        float IRCA = Float.parseFloat(txtirca.getText());

        String instruccion = "insert into cuerpodeagua (idCuerpoAgua,TipoCuerpoAgua,tipoAgua,IRCA,Nombre,Municipio)"
                + " values (" + idCuerpoAgua + ",'" + TipoCuerpoAgua + "','" + TipoAgua + "'," + IRCA + ",'" + Nombre + "','" + Municipio + "')";

        c.ejecutarSQL(instruccion, 1);
        JOptionPane.showMessageDialog(rootPane, "Registro almacenado Satisfactoriamente");
        btn_obtenerdatosActionPerformed(evt);// variable tipo evento evt
        btncancelarActionPerformed(evt);//cancelar para limpiar todo

    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtmunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmunicipioActionPerformed

    }//GEN-LAST:event_txtmunicipioActionPerformed

    private void btn_obtenerdatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obtenerdatosActionPerformed

        String[] encabezado = {"ID ", "TIPO CUERPO", "TIPO AGUA", "IRCA", "NIVEL DE RIESGO", "NOMBRE", "MUNICIPIO"};
        DefaultTableModel modelo = new DefaultTableModel(null, encabezado);
        DefaultTableModel modelo2 = new DefaultTableModel(null, encabezado);
        

        try {

            String instruccion = "Select * from cuerpodeagua ";
            ResultSet rs = c.ejecutarSQL(instruccion, 2);
            modelo.setRowCount(0);
            modelo2.setRowCount(0);

            int i = 0;
            int nca=0; //numero de cuerpo de agua medio o inferior
            while (rs.next()) {
                
                if(rs.getFloat("IRCA")<=35){nca++;}

                ca[i] = new CuerpoDeAgua(rs.getString("TipoCuerpoAgua"),
                        rs.getString("TipoAgua"),
                        rs.getFloat("IRCA"),
                        rs.getString("Nombre"),
                        rs.getInt("idCuerpoAgua"),
                        rs.getString("Municipio"));

                modelo.addRow(new Object[]{
                    rs.getInt("idCuerpoAgua"),
                    rs.getString("TipoCuerpoAgua"),
                    rs.getString("TipoAgua"),
                    rs.getFloat("IRCA"),
                    ca[i].nivel(),
                    rs.getString("Nombre"),
                    rs.getString("Municipio"),});
                
                if(ca[i].nivel().equals("MEDIO")){
                
                    modelo2.addRow(new Object[]{
                    rs.getInt("idCuerpoAgua"),
                    rs.getString("TipoCuerpoAgua"),
                    rs.getString("tipoAgua"),
                    rs.getFloat("IRCA"),
                    ca[i].nivel(),
                    rs.getString("nombre"),
                    rs.getString("municipio"),});
                }
                i++;
            }
            jTextField1.setText(""+nca);
            
        } catch (Exception e) {

        }
        jTable1.setModel(modelo);
        jTable2.setModel(modelo2);
        
        try {
            
            String instruccion = " select nombre,idCuerpoAgua,IRCA from cuerpodeagua "
                    + "where IRCA=(select min(IRCA) from cuerpodeagua)";
            ResultSet rs2 = c.ejecutarSQL(instruccion, 2);
            
            while (rs2.next()) {
            
                jTextField2.setText(rs2.getString("nombre")+" - "+rs2.getString("idCuerpoAgua")+" - "+rs2.getString("IRCA") );
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_obtenerdatosActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        int IdAgua = Integer.parseInt(txtid.getText());
        //aca usamos el boto consultar por medio de id en la base de datos
        try {

            String instruccion = "Select * from cuerpodeagua where idCuerpoAgua=" + IdAgua;
            ResultSet rs = c.ejecutarSQL(instruccion, 2);

            int k = 0;
            while (rs.next()) {
                k = 1;
                txtnombre.setText(rs.getString("Nombre"));
                txtmunicipio.setText(rs.getString("Municipio"));
                txtirca.setText(String.valueOf(rs.getFloat("IRCA")));
                cbo_tipoagua.setSelectedItem(rs.getString("TipoAgua"));
                cbo_cuerpoagua.setSelectedItem(rs.getString("TipoCuerpoAgua"));
            }

            if (k == 1) {
                btnactualizar.setEnabled(true);
                btneliminar.setEnabled(true);
                btn_ingresar.setEnabled(false);
                btnconsultar.setEnabled(false);
            } else {
                btnactualizar.setEnabled(false);
                btneliminar.setEnabled(false);
                btn_ingresar.setEnabled(true);
                btnconsultar.setEnabled(false);
            }

        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void cbo_cuerpoaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_cuerpoaguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_cuerpoaguaActionPerformed

    private void cbo_tipoaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipoaguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_tipoaguaActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        //int idAgua=Integer.parseInt(txtid.getText());
        
        String Nombre = txtnombre.getText();
        int idCuerpoAgua = Integer.parseInt(txtid.getText());
        String Municipio = txtmunicipio.getText();
        String TipoCuerpoAgua = cbo_cuerpoagua.getSelectedItem().toString();
        String TipoAgua = cbo_tipoagua.getSelectedItem().toString();
        float IRCA = Float.parseFloat(txtirca.getText());
        
        String instruccion = "update cuerpodeagua set TipoCuerpoAgua='"+TipoCuerpoAgua+"',"
                + "tipoAgua='"+TipoAgua+"', IRCA="+IRCA+", nombre='"+Nombre+"', "
                + "municipio='"+Municipio+"' where idCuerpoAgua="+idCuerpoAgua;
        c.ejecutarSQL(instruccion, 1);
        
        
        JOptionPane.showMessageDialog(rootPane, "Actualizacion Exitosa");
        
        btncancelarActionPerformed(evt);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        btnactualizar.setEnabled(false);
        btneliminar.setEnabled(false);
        btn_ingresar.setEnabled(false);
        btnconsultar.setEnabled(true);

        txtid.setText("");
        txtmunicipio.setText("");
        txtnombre.setText("");
        txtirca.setText("");
        cbo_tipoagua.setSelectedItem("Dulce");
        cbo_cuerpoagua.setSelectedItem("Rio");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      try {
            int idCuerpoAgua = Integer.parseInt(txtid.getText());

            String instruccion = "delete from cuerpodeagua where idCuerpoAgua=" + idCuerpoAgua;
            c.ejecutarSQL(instruccion, 1);
            
            JOptionPane.showMessageDialog(rootPane, "Eliminacion exitosa..");
            btncancelarActionPerformed(evt);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_obtenerdatos;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<String> cbo_cuerpoagua;
    private javax.swing.JComboBox<String> cbo_tipoagua;
    private javax.swing.JLabel cuerposdeaguamedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtirca;
    private javax.swing.JTextField txtmunicipio;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
